title: Wow
author: fhwustc
email: fhwustc@mail.ustc.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  nothing but self-talking
# social links
twitter_username: your-twitter-handle
github_username:  fhwustc

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
